#!/usr/bin/env bash
installpkgs() {
    debug $DEBUG_INFO "Starting package installation"
    printf "%s\n" "${bold}Installing packages"

    # Get paths for required files
    local pkglist
    local zfs_openrc
    zfs_openrc="$(get_script_path "init.d" "misc")"
    pkglist="$(get_script_path "pkglist.txt" "misc")"


    # Start the progress bar
    (
        echo "10"; sleep 1
        echo "Installing base packages..."; sleep 1
        debug $DEBUG_DEBUG "Installing base packages from pkglist.txt"
        basestrap $INST_MNT - < "$pkglist" >> "$LOG_FILE" 2>&1 && echo "50"
        
        echo "Installing kernel packages..."; sleep 1
        debug $DEBUG_DEBUG "Installing kernel: $INST_LINVAR"
        basestrap $INST_MNT $INST_LINVAR ${INST_LINVAR}-headers linux-firmware >> "$LOG_FILE" 2>&1 && echo "80"
        
        # Install ZFS packages if ZFS is selected
        if [[ $FILESYSTEM == "zfs" ]]; then
            echo "Installing ZFS packages..."; sleep 1
            debug $DEBUG_DEBUG "Installing ZFS packages from yay cache directories"
            basestrap -U $INST_MNT /home/artix/.cache/yay/zfs-dkms-staging-git/*.pkg.tar.zst >> "$LOG_FILE" 2>&1
            basestrap -U $INST_MNT /home/artix/.cache/yay/zfs-utils-staging-git/*.pkg.tar.zst >> "$LOG_FILE" 2>&1
            debug $DEBUG_DEBUG "Copying init.d scripts for ZFS"
            cp -r "$zfs_openrc" $INST_MNT/etc/ >> "$LOG_FILE" 2>&1 && echo "90"
        fi
        
        echo "Copying pacman configuration..."; sleep 1
        debug $DEBUG_DEBUG "Copying pacman configuration files"
        rm -rf $INST_MNT/etc/pacman.d >> "$LOG_FILE" 2>&1
        rm $INST_MNT/etc/pacman.conf >> "$LOG_FILE" 2>&1
        cp -r /etc/pacman.d $INST_MNT/etc >> "$LOG_FILE" 2>&1
        cp /etc/pacman.conf $INST_MNT/etc >> "$LOG_FILE" 2>&1 && echo "100"
    ) | dialog --gauge "Installing packages..." 10 70 0

    # Check if the packages were installed successfully
    if [[ $? -ne 0 ]]; then
        debug $DEBUG_ERROR "Package installation failed"
        error "Error installing packages!"
    fi

    debug $DEBUG_INFO "Package installation completed successfully"
    printf "%s\n" "${bold}Packages installed successfully!"
}