#!/usr/bin/env bash
bold=$(tput setaf 2 bold)      # makes text bold and sets color to 2
bolderror=$(tput setaf 3 bold) # makes text bold and sets color to 3
normal=$(tput sgr0)            # resets text settings back to normal

# Function to install ZFS modules
# This function is called before the ZFS root pool and datasets have been created
installzfs() {
    printf "%s\n" "${bold}# Installing the ZFS modules"

    # Get path for ZFS OpenRC package
    local zfs_openrc
    local zfs_dkms
    local zfs_utils
    zfs_openrc="$(get_script_path "zfs-openrc.pkg.tar.zst" "misc")"
    zfs_dkms="$(get_script_path "zfs-dkms.pkg.tar.zst" "misc")"
    zfs_utils="$(get_script_path "zfs-utils.pkg.tar.zst" "misc")"

    # Start the progress bar
    (
        echo "10"; sleep 1
        echo "Installing ZFS packages..."; sleep 1
        pacman -Sy --noconfirm --needed  autoconf automake fakeroot >> "$LOG_FILE" 2>&1 && echo "20"
        pacman -U --noconfirm  --needed "$zfs_dkms" "$zfs_utils" >> "$LOG_FILE" 2>&1 && echo "30"
        echo "Installing ZFS OpenRC package..."; sleep 1
        pacman -U --noconfirm --needed "$zfs_openrc" >> "$LOG_FILE" 2>&1 && echo "70"
        rc-service zfs-zed start && echo "80"
        echo "Loading ZFS kernel module..."; sleep 1
        modprobe zfs && echo "90"
        zgenhostid -f && echo "100"
    ) | dialog --gauge "Installing ZFS modules..." 10 70 0

    # Check if ZFS was installed successfully
    if ! modinfo zfs &>/dev/null; then
        error "Error installing ZFS!"
    fi

    printf "%s\n" "${bold}Done!"
}
